#!/bin/bash

TEMP=`getopt -o s:y:m:d: --long server:,year:,month:,day: \
     -n 'irc-logparse' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

year=`date +%Y -d "yesterday"`
month=`date +%m -d "yesterday"`
day=`date +%d -d "yesterday"`
server="irclogs.ubuntu.com"

while true ; do
    case "$1" in
        -s|--server) server="$2" ; shift 2 ;;
        -y|--year) year="$2" ; shift 2 ;;
        -m|--month) month="$2"; shift 2 ;;
        -d|--day) day="$2"; shift 2 ;;
        --) shift ; break ;;
        *) echo "$1 is not a valid option" ; exit 1 ;;
    esac
done

for arg do
    d=`mktemp -d`
