#!/bin/bash

TEMP=`getopt -o s:y:m:d: --long server:,year:,month:,day: \
     -n 'irc-logparse' -- "$@"`

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

eval set -- "$TEMP"

year=`date +%Y -d "yesterday"`
month=`date +%m -d "yesterday"`
day=`date +%d -d "yesterday"`
server="irclogs.ubuntu.com"

while true ; do
    case "$1" in
        -s|--server) server="$2" ; shift 2 ;;
        -y|--year) year="$2" ; shift 2 ;;
        -m|--month) month="$2"; shift 2 ;;
        -d|--day) day="$2"; shift 2 ;;
        --) shift ; break ;;
        *) echo "$1 is not a valid option" ; exit 1 ;;
    esac
done

d=`mktemp -d`
for arg do
    f="$d/$year-$month-$day-$arg.txt"
    wget "http://$server/$year/$month/$day/%23$arg.txt" -O "$f" > /dev/null 2>&1
    echo "$arg $year/$month/$day"
    d=`cat $f | egrep -v "^===" | sed -e 's/  \* / /g' -e 's/[<>]//g' | awk '{ print $2 }' | sort | uniq -c | sort -nk1`
    n=`echo "$d" | wc -l`;
    m=0
    for i in `echo "$d" | awk '{print $1}'`; do
        m="$(($m+$i))"
    done
    echo "$d"
    echo "Active Users: $(($n-1)). Total messages: $m";
done
